---
title: "Week3-Rmarkdown"
author: "Tianheng Z."
date: "2021/10/10"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1.Random Experiments, events and sample spaces
```{r,results='hide',warning=FALSE}
#Load the library
library(tidyverse)
```
# 2.Tidy data and iteration
## 2.1 Missing Data and iteration

```{r}
#Should use the purr package
impute_by_mean<-function(x){
  mu<-mean(x,na.rm=1) # first compute the mean of x
  impute_f<-function(z){ # coordinate-wise imputation
    if(is.na(z)){
    return(mu) # if z is na replace with mean
} else{
  return(z) # otherwise leave in place
  }
}
  return(map_dbl(x,impute_f)) # apply the map function to impute across vector
}
```

Now Create the impute_by_median
```{r}
impute_by_median <- function(x){
  med <- median(x,na.rm = 1)
  impute_f <- function(z){
    if(is.na(z)){
      return(med)
    }
    else{
      return(z)
    }
  }
  return(map_dbl(x,impute_f))
  
}
#Test
v <- c(1,2,NA,4)
impute_by_median(v)
```

Now Create df_xy
```{r}
x <- seq(0,10,0.1)
y <- 5 *x +1
df_xy <- data.frame(x,y)
df_xy %>% head(5)
```

```{r}
df_xy %>% mutate(z = map2_dbl(x,y,~.x+.y)) %>% head(5)
```

```{r}
sometimes_missing <- function(index,value){
  mis_fuc <- function(a,b){
    if(a %% 5 ==0){
      return(NA)
    }
    else{
      return(b)
    }
  }
  return (map2_dbl(index,value,mis_fuc))
}
sometimes_missing(14,25)
sometimes_missing(15,25)
```

```{r}
#Generate df_xy_missing
x <- df_xy$x
y <- map2_dbl(row_number(df_xy$y),df_xy$y,sometimes_missing)
df_xy_missing <- data.frame(x,y)
df_xy_missing %>% head(10)
```

```{r}
x <- df_xy$x
y <- impute_by_median(df_xy_missing$y)
df_xy_imputed <- data.frame(x,y) 
df_xy_imputed %>% head(10)
```

Combine the df
```{r}
df_xy<-df_xy%>%
mutate(source="original")
df_xy_missing<-df_xy_missing%>%
mutate(source="corrupted")
df_xy_imputed<-df_xy_imputed%>%
mutate(source="imputed")
df_combined<-rbind(df_xy,df_xy_missing,df_xy_imputed)

ggplot(df_combined,aes(x=x,y=y,color = source)) + geom_point()+
  facet_wrap(~source) + geom_smooth(method = "lm")
```

## 2.2 Tidying data with pivot functions
```{r}
if(!require("readxl"))
install.packages("readxl")
```
```{r,results='hide'}
library(readxl)
library(tidyverse)
folder_path <- paste("C:\\Users\\zth2\\Desktop\\Bristol\\SCEM\\Week3\\FirstRproject", "\\Week3",sep = "")
file_name <- "HockeyLeague.xlsx"

file_path <- paste(folder_path,file_name,sep = "\\")
wins_data_frame <- read_excel(file_path,sheet = "Wins")
```

```{r}
wins_data_frame %>%tibble() %>% select(1:5) %>% head(3)
```

### Not tidy data
```{r}
wins_tidy <- wins_data_frame %>% 
  rename(Team = ...1) %>% 
  pivot_longer(cols = !Team,names_to = "Year") %>% 
  separate(col = value,into = c("Wins","Total"),sep = "of")
wins_tidy %>% dim()

```

```{r}
wins_tidy %>% head(5)
```

### Create losses_tidy
```{r}
losses_data_frame <- read_excel(file_path,sheet = "Losses")
losses_tidy <- losses_data_frame %>%
  tibble() %>%
  rename(Team = ...1) %>%
  pivot_longer(cols = !Team,names_to = "Year") %>%
  separate(col = value, into= c("Losses","Total"),sep = "of")

losses_tidy %>%head(5)
```

### Combine two dataframe
```{r}
hockey_df <- wins_tidy %>% 
  inner_join(losses_tidy) %>%
  mutate(Wins = as.integer(Wins),Total = as.integer(Total),
         Losses = as.integer(Losses)) %>%
  mutate(Draws = Total - Wins- Losses,
         Wins_rt = Wins/Total,
         Losses_rt = Losses / Total,
         Draws_rt = Draws/Total)

  
  
hockey_df %>% head(5)

```

### Conclude
```{r}
hockey_df %>% group_by(Team)%>% summarise(median_win_rt = median(Wins_rt),
                        mean_win_rt = mean(Wins_rt),
                        median_Losses_rt = median(Losses_rt),
                        mean_Losses_rt = mean(Losses_rt),
                        median_Draws_rt = median(Draws_rt),
                        mean_Draws_rt = mean(Draws_rt)) %>% 
  arrange(desc(median_win_rt))
```

## 2.3 Most correlated variables
```{r}
max_cor_var<-function(df,col_name){
# function to determine the variable with maximal correlation
v_col<-df%>%select(all_of(col_name))
# extract variable based on col_name
df_num<-df%>%
select_if(is.numeric)%>%
select(-all_of(col_name))
# select all numeric variables excluding col_name
correlations<-unlist(map(df_num,
function(x){cor(x,v_col,use="complete.obs")}))
# compute correlations with all other numeric variables
max_abs_cor_var<-names(which(abs(correlations)==max(abs(correlations))))
# extract the variable name
cor<-as.double(correlations[max_abs_cor_var])
# compute the correlation
return(data.frame(var_name=max_abs_cor_var,cor=cor))
# return dataframe
}
```

```{r}

top_correlates_by_var <- function(df){
  df_names <- names(df)
  
  #Five numeric cols
  df_num2 <- df %>% select_if(is.numeric) %>%names()
  #print(df_num2)
  
  df_map_func <- function(df_colname){
    df_num <- df%>% select_if(is.numeric) %>%
      select(-all_of(df_colname))  #other 4 cols
    
    df_mine <- df %>% select(df_colname)
    
    #print(df_colname)
    correlations<-unlist(map(df_num,function(x){cor(x,df_mine,use="complete.obs")}))
    # compute correlations with all other numeric variables
    max_abs_cor_var<-names(which(abs(correlations)==max(abs(correlations))))
    #print(max_abs_cor_var)
    # extract the variable name
    cor<-as.double(correlations[max_abs_cor_var])
    return(as.character(max_abs_cor_var))
  }
  
  #Should add results first then change the names
  results <- map_chr(df_num2,df_map_func)
  results_df<- as.data.frame(matrix(nrow = 0,ncol = length(df_num2))) 
  final_results <- results_df %>%rbind(results)
  colnames(final_results) <- df_num2

  return(final_results %>% mutate(across(everything(),as.character)))
  
}


```

```{r}
library(palmerpenguins)
penguins%>%top_correlates_by_var()
```

```{r}
Adelie_re <- penguins %>% filter(species == "Adelie") %>% top_correlates_by_var()
Gentoo_re <- penguins %>% filter(species == "Gentoo") %>% top_correlates_by_var()
Chinstrap_re <- penguins %>% filter(species == "Chinstrap") %>% top_correlates_by_var()

as_tibble(rbind(Adelie_re,Gentoo_re,Chinstrap_re)) %>% 
  mutate(species = c("Adelie","Gentoo","Chinstrap")) %>%
  select(6,1:5) %>% mutate(across(everything(),as.character),species = as.factor(species))
```

# 3. Elementary set theory

# 4. Introduction to probability





